Repository pytorch/PiPPy, pull requests merged in 2022-07, with the labels that each got.

#271 Temporary disable DistilBert and Deberta models in HF tests
  test/hf_test.py
Labels: cla signed

#275 Porting changes from pippy_t5_translation.py
  examples/slurm/hf/t5/pippy_t5.py
Labels: cla signed

#278 [spmd] import spmd package
  .github/workflows/ci_tests.yaml
  .github/workflows/code-quality.yml
  .github/workflows/spmd_tests.yaml
  spmd/__init__.py
  spmd/requirements.txt
  spmd/requirements_dev.txt
  spmd/tensor/README.md
  spmd/tensor/__init__.py
  spmd/tensor/api.py
  spmd/tensor/device_mesh.py
  spmd/tensor/ops/__init__.py
  spmd/tensor/ops/math_ops.py
  spmd/tensor/ops/matrix_ops.py
  spmd/tensor/ops/tensor_ops.py
  spmd/tensor/ops/utils.py
  spmd/tensor/placement_types.py
  spmd/tensor/redistribute.py
  spmd/tensor/utils.py
  test/spmd/__init__.py
  test/spmd/tensor/README.md
  test/spmd/tensor/__init__.py
  test/spmd/tensor/demo.py
  test/spmd/tensor/test_ddp.py
  test/spmd/tensor/test_ops.py
  test/spmd/tensor/test_tensor.py
  test/spmd/test_utils.py
Labels: cla signed

#282 Move chunks to PipelineDriver c-tor
  README.md
  example.py
  example_train.py
  examples/slurm/hf/bert/pippy_bert.py
  examples/slurm/hf/gpt2/pippy_gpt2.py
  examples/slurm/hf/t5/pippy_t5.py
  examples/slurm/mnist/pippy_mnist.py
  examples/slurm/resnet/pippy_resnet.py
  pippy/PipelineDriver.py
  test/local_test_ddp.py
  test/local_test_forward.py
  test/local_test_forward_backward.py
  test/local_test_forward_hf_bert.py
  test/local_test_forward_hf_gpt2.py
  test/local_test_null_coalesce_accumulate.py
  test/local_test_visualizer.py
Labels: cla signed, PiPPy

#284 Fix local_test_forward_auto_parallel.py chunks in PipelineDriver c-tor
  test/local_test_forward_auto_parallel.py
Labels: cla signed

#287 Fix run_until function
  pippy/PipelineDriver.py
Labels: cla signed

#279 Fix passing torch.Size over pipe split
  pippy/IR.py
  pippy/PipelineDriver.py
  test/local_test_forward_backward.py
Labels: cla signed, PiPPy

#289 [SPMD] Enable black lint for code in `spmd`
  .github/workflows/code-quality.yml
  spmd/__init__.py
  spmd/tensor/__init__.py
  spmd/tensor/api.py
  spmd/tensor/device_mesh.py
  spmd/tensor/ops/math_ops.py
  spmd/tensor/ops/matrix_ops.py
  spmd/tensor/ops/tensor_ops.py
  spmd/tensor/ops/utils.py
  spmd/tensor/redistribute.py
  spmd/tensor/utils.py
  test/spmd/tensor/demo.py
  test/spmd/tensor/test_ddp.py
  test/spmd/tensor/test_ops.py
  test/spmd/tensor/test_tensor.py
  test/spmd/test_utils.py
Labels: cla signed

#288 [spmd] rewrite redistribute with autograd function
  spmd/tensor/api.py
  spmd/tensor/device_mesh.py
  spmd/tensor/placement_types.py
  spmd/tensor/redistribute.py
  test/spmd/tensor/test_redistribute.py
  test/spmd/tensor/test_tensor.py
Labels: cla signed

#293 Temporary pin nightly to 2022-07-19
  requirements.txt
Labels: cla signed

#280 Manual add_split_points for T5
  examples/slurm/hf/t5/pippy_t5.py
Labels: cla signed, PiPPy

#291 [spmd] clean up some code
  spmd/tensor/ops/math_ops.py
  spmd/tensor/ops/matrix_ops.py
  spmd/tensor/ops/utils.py
  spmd/tensor/placement_types.py
  spmd/tensor/redistribute.py
  test/spmd/tensor/README.md
Labels: cla signed

#296 Fix OPTForSequenceClassification HF test
  test/hf_test.py
Labels: cla signed

#294 unittest.TestCase entrypoints for integration tests
  test/local_test_ddp.py
  test/local_test_forward.py
  test/local_test_forward_auto_parallel.py
  test/local_test_forward_backward.py
  test/local_test_null_coalesce_accumulate.py
  test/local_test_visualizer.py
Labels: cla signed

#297 [SPMD] Enable Pyre for type annotation check
  .github/workflows/code-quality.yml
  .gitignore
  .pyre_configuration
  spmd/__init__.py
  spmd/requirements_dev.txt
  spmd/tensor/api.py
  spmd/tensor/device_mesh.py
  spmd/tensor/ops/matrix_ops.py
  spmd/tensor/ops/tensor_ops.py
  spmd/tensor/ops/utils.py
  spmd/tensor/redistribute.py
  spmd/tensor/utils.py
Labels: cla signed

#304 Add copyright headers
  test/fx/named_tup.py
  test/fx/quantization.py
  test/fx/test_dce_pass.py
  test/fx/test_future.py
  test/fx/test_fx_const_fold.py
  test/fx/test_fx_param_shape_control_flow.py
  test/fx/test_gradual_type.py
  test/fx/test_pass_infra.py
  test/fx/test_subgraph_rewriter.py
  test/fx/test_z3_gradual_types.py
Labels: cla signed, fx

#305 Add copyright headers
  test/test_fx.py
  test/test_fx_experimental.py
Labels: cla signed

#306 Revert "Temporary pin nightly to 2022-07-19 (#293)"
  requirements.txt
Labels: cla signed

#310 [spmd] set up package install for spmd
  .gitignore
  spmd/setup.py
  spmd/version.txt
Labels: cla signed

#312 [SPMD] Split `test_ops.py` into multiple files
  test/spmd/tensor/test_math_ops.py
  test/spmd/tensor/test_matrix_ops.py
  test/spmd/tensor/test_tensor_ops.py
Labels: cla signed

#311 [TP] Enable Dropout for DT and add test for activations
  spmd/__init__.py
  spmd/setup.py
  spmd/tensor/ops/__init__.py
  spmd/tensor/ops/dropout.py
  spmd/tensor/ops/math_ops.py
  spmd/tensor/ops/matrix_ops.py
  test/spmd/tensor/test_elementwise_ops.py
Labels: cla signed

#313 [spmd] Support N-D DeviceMesh
  spmd/__init__.py
  spmd/tensor/api.py
  spmd/tensor/device_mesh.py
  spmd/tensor/ops/dropout.py
  spmd/tensor/ops/math_ops.py
  spmd/tensor/redistribute.py
  test/spmd/tensor/test_device_mesh.py
  test/spmd/tensor/test_tensor.py
Labels: cla signed
