Repository pytorch/PiPPy, pull requests merged in 2022-08, with the labels that each got.

#316 Bloom models fix
  test/hf_test.py
Labels: cla signed

#317 Make mypy and flake8 happy and main branch green
  .flake8
  pippy/IR.py
Labels: cla signed, fx

#320 Add strict mode for DT and more checks and error …
  spmd/__init__.py
  spmd/tensor/api.py
Labels: cla signed

#323 Fix warnings module import in fx code
  pippy/fx/_symbolic_trace.py
  pippy/fx/operator_schemas.py
Labels: cla signed, fx

#322 [spmd] switch device mesh collective to use mesh dim groups
  spmd/tensor/device_mesh.py
  test/spmd/tensor/test_device_mesh.py
Labels: cla signed

#328 [spmd] add __torch_function__ to allow us override on python level
  spmd/tensor/api.py
Labels: cla signed

#327 Enable tp ops needed in ViT model with unit test
  spmd/tensor/api.py
  spmd/tensor/ops/__init__.py
  spmd/tensor/ops/tp_sharding_ops.py
  test/spmd/tensor/test_tp_sharding_ops.py
Labels: cla signed

#329 [spmd] add multi-d tests for all_reduce, broadcast and scatter
  test/spmd/tensor/test_device_mesh.py
Labels: cla signed

#330 [spmd] Rename Tensor to DTensor and change APIs
  spmd/__init__.py
  spmd/tensor/__init__.py
  spmd/tensor/api.py
  spmd/tensor/device_mesh.py
  spmd/tensor/ops/dropout.py
  spmd/tensor/ops/math_ops.py
  spmd/tensor/ops/matrix_ops.py
  spmd/tensor/ops/tensor_ops.py
  spmd/tensor/ops/tp_sharding_ops.py
  spmd/tensor/ops/utils.py
  spmd/tensor/redistribute.py
  spmd/tensor/utils.py
  test/spmd/tensor/demo.py
  test/spmd/tensor/test_ddp.py
  test/spmd/tensor/test_device_mesh.py
  test/spmd/tensor/test_elementwise_ops.py
  test/spmd/tensor/test_math_ops.py
  test/spmd/tensor/test_matrix_ops.py
  test/spmd/tensor/test_redistribute.py
  test/spmd/tensor/test_tensor.py
  test/spmd/tensor/test_tensor_ops.py
  test/spmd/tensor/test_tp_sharding_ops.py
Labels: cla signed

#319 [spmd] enable distributed tensor work with torch.Tensor in autograd
  spmd/__init__.py
  spmd/tensor/api.py
  spmd/tensor/device_mesh.py
  spmd/tensor/ops/dropout.py
  spmd/tensor/ops/math_ops.py
  spmd/tensor/ops/matrix_ops.py
  spmd/tensor/ops/tensor_ops.py
  spmd/tensor/ops/tp_sharding_ops.py
  spmd/tensor/redistribute.py
  test/spmd/tensor/test_ddp.py
  test/spmd/tensor/test_device_mesh.py
  test/spmd/tensor/test_matrix_ops.py
  test/spmd/tensor/test_redistribute.py
  test/spmd/tensor/test_tensor.py
Labels: cla signed

#321 [spmd] separate sharding propagation with compute
  spmd/tensor/api.py
  spmd/tensor/device_mesh.py
  spmd/tensor/dispatch.py
  spmd/tensor/ops/matrix_ops.py
  spmd/tensor/ops/pointwise_ops.py
  spmd/tensor/ops/prop_rules.py
  spmd/tensor/ops/tensor_ops.py
  spmd/tensor/ops/tp_sharding_ops.py
  spmd/tensor/ops/utils.py
  spmd/tensor/placement_types.py
  spmd/tensor/utils.py
  test/spmd/tensor/test_math_ops.py
  test/spmd/tensor/test_matrix_ops.py
  test/spmd/tensor/test_pointwise_ops.py
Labels: cla signed

#340 Finish all lint tests even if previous one fails
  .github/workflows/code-quality.yml
Labels: cla signed, better engineering

#334 Move stage_backward etc to a separate file
  pippy/IR.py
  pippy/PipelineDriver.py
  pippy/backward.py
Labels: cla signed, PiPPy, better engineering

#343 [spmd] enable contiguous in dispatch, and explicit relu/gelu
  spmd/__init__.py
  spmd/tensor/device_mesh.py
  spmd/tensor/dispatch.py
  spmd/tensor/ops/__init__.py
  spmd/tensor/ops/pointwise_ops.py
  spmd/tensor/ops/prop_rules.py
  spmd/tensor/ops/tensor_ops.py
  spmd/tensor/ops/tp_sharding_ops.py
  test/spmd/tensor/test_pointwise_ops.py
  test/spmd/tensor/test_tensor_ops.py
  test/spmd/tensor/test_tp_sharding_ops.py
Labels: cla signed

#332 Fix #331: improve Pipeline Driver issuance efficiency
  examples/slurm/hf/t5/pippy_t5.py
  examples/slurm/hf/t5/pippy_wrapper.sh
  pippy/PipelineDriver.py
  test/pippy_wrapper.sh
Labels: cla signed, PiPPy

#345 [DTensor] Add tests for sigmoid ops
  spmd/tensor/ops/pointwise_ops.py
  test/spmd/tensor/test_pointwise_ops.py
Labels: cla signed

#344 [SPMD] Add one Megatron simple e2e test and remove relative import
  spmd/tensor/api.py
  spmd/tensor/device_mesh.py
  spmd/tensor/ops/matrix_ops.py
  spmd/tensor/ops/pointwise_ops.py
  spmd/tensor/ops/tp_sharding_ops.py
  spmd/test/_utils.py
  test/spmd/tensor/test_ddp.py
  test/spmd/tensor/test_device_mesh.py
  test/spmd/tensor/test_math_ops.py
  test/spmd/tensor/test_matrix_ops.py
  test/spmd/tensor/test_megatron_example.py
  test/spmd/tensor/test_pointwise_ops.py
  test/spmd/tensor/test_redistribute.py
  test/spmd/tensor/test_tensor.py
  test/spmd/tensor/test_tensor_ops.py
  test/spmd/tensor/test_tp_sharding_ops.py
Labels: cla signed, better engineering

#351 Add copyright header
  spmd/tensor/ops/pointwise_ops.py
Labels: cla signed

#349 Revert "Fix #331: improve Pipeline Driver issuance efficiency (#332)"
  examples/slurm/hf/t5/pippy_t5.py
  examples/slurm/hf/t5/pippy_wrapper.sh
  pippy/PipelineDriver.py
  test/pippy_wrapper.sh
Labels: cla signed

#357 Fix missing noop ValueReference in _null_coalesce_accumulate
  pippy/PipelineDriver.py
Labels: cla signed

#356 Cancel CI on previous commit when a new commit is pushed
  .github/workflows/ci_tests.yaml
Labels: cla signed, better engineering

#346 Fix code returned from docker to GHA
  .github/workflows/ci_tests.yaml
  .github/workflows/gpu_tests.sh
Labels: cla signed, better engineering

#362 Skip Donut SWIN models in hf_test.py
  test/hf_test.py
Labels: cla signed

#355 Remove slurm directory
  .github/workflows/ci_tests.yaml
  .github/workflows/gpu_tests.sh
  examples/hf/bert/pippy_bert.py
  examples/hf/bert/pippy_sbatch.sh
  examples/hf/bert/pippy_wrapper.sh
  examples/hf/gpt2/README.md
  examples/hf/gpt2/pippy_gpt2.py
  examples/hf/gpt2/pippy_sbatch.sh
  examples/hf/gpt2/pippy_wrapper.sh
  examples/hf/t5/pippy_sbatch_16_gpus_per_node.sh
  examples/hf/t5/pippy_sbatch_8_gpus_per_node.sh
  examples/hf/t5/pippy_t5.py
  examples/hf/t5/pippy_wrapper.sh
  examples/hf/t5/t5_200m_config.json
  examples/hf/t5/t5_3b_config.json
  examples/mnist/.gitignore
  examples/mnist/ddp_mnist.py
  examples/mnist/local_mnist.py
  examples/mnist/pippy_mnist.py
  examples/mnist/pippy_sbatch.sh
  examples/mnist/pippy_wrapper.sh
  examples/resnet/.gitignore
  examples/resnet/local_resnet.py
  examples/resnet/pippy_resnet.py
  examples/resnet/pippy_sbatch.sh
  examples/resnet/pippy_wrapper.sh
  examples/resnet/resnet.py
Labels: cla signed, better engineering

#367 Separate pippy and spmd CI and speed up spmd CI
  .github/workflows/code-quality.yml
  .github/workflows/pippy_tests.yaml
  .github/workflows/spmd_tests.yaml
Labels: cla signed, better engineering

#369 HF examples
  .github/workflows/code-quality.yml
  examples/hf/language-modeling/README.md
  examples/hf/language-modeling/requirements.txt
  examples/hf/language-modeling/run_clm.py
  examples/hf/language-modeling/run_clm_no_trainer.py
  examples/hf/language-modeling/run_mlm.py
  examples/hf/language-modeling/run_mlm_no_trainer.py
  examples/hf/text-classification/README.md
  examples/hf/text-classification/requirements.txt
  examples/hf/text-classification/run_glue.py
  examples/hf/text-classification/run_glue_no_trainer.py
  examples/hf/text-classification/run_xnli.py
  examples/hf/translation/README.md
  examples/hf/translation/requirements.txt
  examples/hf/translation/run_translation.py
  examples/hf/translation/run_translation_no_trainer.py
Labels: cla signed

#359 HF examples with PiPPy
  .github/workflows/pippy_tests.yaml
  examples/hf/language-modeling/run_clm.py
  examples/hf/language-modeling/run_mlm.py
  examples/hf/text-classification/run_glue.py
  examples/hf/translation/run_translation.py
  pippy/hf/__init__.py
  pippy/hf/bart.py
  pippy/hf/bert.py
  pippy/hf/gpt2.py
  pippy/hf/roberta.py
  pippy/hf/t5.py
  pippy/hf/utils.py
Labels: cla signed

#354 [spmd] Implement basic auto redistribute for DTensor
  spmd/tensor/api.py
  spmd/tensor/dispatch.py
  spmd/tensor/ops/math_ops.py
  spmd/tensor/ops/matrix_ops.py
  spmd/tensor/ops/pointwise_ops.py
  spmd/tensor/ops/prop_rules.py
  spmd/tensor/ops/tensor_ops.py
  spmd/tensor/placement_types.py
  spmd/tensor/redistribute.py
  spmd/tensor/utils.py
  test/spmd/tensor/test_math_ops.py
  test/spmd/tensor/test_matrix_ops.py
  test/spmd/tensor/test_redistribute.py
Labels: cla signed

#371 Do not run CI for previous commit if PR gets updated
  .github/workflows/pippy_tests.yaml
  .github/workflows/spmd_tests.yaml
Labels: cla signed, better engineering

#373 PiPPyTrainer and PiPPySeq2SeqTrainer
  examples/hf/language-modeling/run_clm.py
  examples/hf/language-modeling/run_mlm.py
  examples/hf/text-classification/run_glue.py
  examples/hf/translation/run_translation.py
  pippy/hf/__init__.py
  pippy/hf/utils.py
Labels: cla signed

#374 Replace multiple HF tracers with a single one
  examples/hf/bert/pippy_bert.py
  examples/hf/gpt2/pippy_gpt2.py
  examples/hf/t5/pippy_t5.py
  pippy/hf/__init__.py
  test/local_test_forward_hf_bert.py
  test/local_test_forward_hf_gpt2.py
Labels: cla signed, huggingface, better engineering

#378 Change PiPPy test workflow name
  .github/workflows/pippy_tests.yaml
Labels: cla signed

#375 [spmd] Add reduction rule, use reduction rule in sum
  spmd/tensor/ops/math_ops.py
  spmd/tensor/ops/matrix_ops.py
  spmd/tensor/ops/pointwise_ops.py
  spmd/tensor/ops/tp_sharding_ops.py
  spmd/tensor/ops/utils.py
  spmd/tensor/placement_types.py
  test/spmd/tensor/test_math_ops.py
Labels: cla signed

#358 Support for multi-dim distribute and redistribute
  spmd/__init__.py
  spmd/tensor/device_mesh.py
  spmd/tensor/redistribute.py
  test/spmd/tensor/test_redistribute.py
Labels: cla signed

#379 [spmd] Add tensor shape to spec and rename spec
  spmd/__init__.py
  spmd/tensor/api.py
  spmd/tensor/dispatch.py
  spmd/tensor/ops/math_ops.py
  spmd/tensor/ops/matrix_ops.py
  spmd/tensor/placement_types.py
  spmd/tensor/utils.py
  test/spmd/tensor/test_dtensor.py
  test/spmd/tensor/test_math_ops.py
Labels: cla signed

#381 [spmd] enable simple megatron example
  test/spmd/tensor/test_megatron_example.py
Labels: cla signed

#380 Replace multiple run_worker with a single one
  examples/hf/bert/pippy_bert.py
  examples/hf/gpt2/pippy_gpt2.py
  examples/hf/language-modeling/run_clm.py
  examples/hf/language-modeling/run_mlm.py
  examples/hf/t5/pippy_t5.py
  examples/hf/text-classification/run_glue.py
  examples/hf/translation/run_translation.py
  examples/mnist/pippy_mnist.py
  examples/resnet/pippy_resnet.py
  pippy/__init__.py
  pippy/hf/__init__.py
  pippy/hf/utils.py
  pippy/utils.py
  test/local_test_ddp.py
  test/local_test_forward.py
  test/local_test_forward_auto_parallel.py
  test/local_test_forward_backward.py
  test/local_test_forward_hf_bert.py
  test/local_test_forward_hf_gpt2.py
  test/local_test_null_coalesce_accumulate.py
  test/local_test_visualizer.py
  test/test_commons.py
Labels: high-pri, cla signed, 2022 H2, better engineering

#389 Add copyright header
  pippy/utils.py
Labels: cla signed

#387 add test for nd device mesh
  test/spmd/tensor/test_device_mesh.py
Labels: cla signed, better engineering

#385 [spmd] add support for inplace op registration
  spmd/tensor/dispatch.py
  spmd/tensor/ops/pointwise_ops.py
  test/spmd/tensor/test_pointwise_ops.py
  test/spmd/tensor/test_tensor_ops.py
Labels: cla signed

#392 fix lint
  mypy.ini
  spmd/tensor/dispatch.py
Labels: cla signed

#391 Add driver process group setter
  pippy/hf/utils.py
  pippy/utils.py
  test/local_test_ddp.py
Labels: cla signed

#388 Add CUDA support for HF examples
  pippy/hf/utils.py
  pippy/utils.py
Labels: cla signed

#324 Implement shape ops
  spmd/tensor/dispatch.py
  spmd/tensor/ops/__init__.py
  spmd/tensor/ops/tp_sharding_ops.py
  spmd/tensor/ops/view_ops.py
  test/spmd/tensor/test_tp_sharding_ops.py
  test/spmd/tensor/test_view_ops.py
Labels: cla signed

#393 [spmd] fix out variant return in master
  spmd/tensor/dispatch.py
Labels: cla signed

#372 [REMERGE] Fix #331: improve Pipeline Driver issuance efficiency
  .github/workflows/pippy_tests.yaml
  examples/hf/t5/pippy_t5.py
  examples/hf/t5/pippy_wrapper.sh
  pippy/PipelineDriver.py
  pippy/utils.py
  test/pippy_wrapper.sh
Labels: cla signed

#394 Finer trigger rule for pippy and spmd tests
  .github/workflows/pippy_gpu_tests.sh
  .github/workflows/pippy_tests.yaml
  .github/workflows/spmd_tests.yaml
Labels: cla signed

#395 Fall back to CPU if no GPU found
  pippy/utils.py
Labels: cla signed

#397 Downsize local_ddp_test
  test/local_test_ddp.py
Labels: cla signed, better engineering

#400 Copyright Header
  spmd/tensor/ops/view_ops.py
Labels: cla signed

#398 Consolidate HF model tests
  .github/workflows/pippy_tests.yaml
Labels: cla signed, better engineering

#399 Consolidate DDP test into integration tests
  .github/workflows/pippy_tests.yaml
Labels: cla signed, better engineering

#405 Ask stage executor to trigger lr scheduler stepping for us
  pippy/PipelineDriver.py
Labels: cla signed

#407 Disable save_model() due to pickling error
  examples/hf/language-modeling/run_clm.py
  examples/hf/language-modeling/run_mlm.py
  examples/hf/text-classification/run_glue.py
  examples/hf/text-classification/run_xnli.py
  examples/hf/translation/run_translation.py
Labels: cla signed

#401 [spmd] use ops db for testing
  spmd/tensor/dispatch.py
  spmd/tensor/ops/tensor_ops.py
  spmd/test/_utils.py
  spmd/test/dtensor_lagging_op_db.py
  spmd/test/gen_dtensor_lagging_op_db.py
  test/spmd/tensor/test_dtensor_ops.py
Labels: cla signed

#414 Limit PyTorch version to make CI green
  .github/workflows/pippy_tests.yaml
  requirements.txt
Labels: cla signed

#416 [spmd] rename _utils to common_utils
  spmd/test/common_utils.py
  test/spmd/tensor/test_ddp.py
  test/spmd/tensor/test_device_mesh.py
  test/spmd/tensor/test_dtensor.py
  test/spmd/tensor/test_dtensor_ops.py
  test/spmd/tensor/test_math_ops.py
  test/spmd/tensor/test_matrix_ops.py
  test/spmd/tensor/test_megatron_example.py
  test/spmd/tensor/test_pointwise_ops.py
  test/spmd/tensor/test_redistribute.py
  test/spmd/tensor/test_tensor_ops.py
  test/spmd/tensor/test_tp_sharding_ops.py
  test/spmd/tensor/test_view_ops.py
Labels: cla signed

#409 [SPMD] Update `aten.mm` and `aten.addmm` to use einop rule
  spmd/tensor/ops/matrix_ops.py
  test/spmd/tensor/test_matrix_ops.py
Labels: cla signed

#417 t5-large and t5-3b work
  examples/hf/translation/run_translation.py
  examples/hf/translation/t5-3b_config.json
  pippy/PipelineDriver.py
  pippy/hf/utils.py
  pippy/utils.py
Labels: cla signed

#415 [spmd] by default disable the fallback mode
  spmd/tensor/dispatch.py
  spmd/tensor/ops/math_ops.py
  spmd/tensor/ops/pointwise_ops.py
  spmd/tensor/ops/tensor_ops.py
  test/spmd/tensor/test_dtensor_ops.py
  test/spmd/tensor/test_view_ops.py
Labels: cla signed

#333 [SPMD] Enable GPU CI for Distributed Tensor
  .github/workflows/docker/Dockerfile
  .github/workflows/spmd_gpu_tests.sh
  .github/workflows/spmd_tests.yaml
  .github/workflows/wait_for_ssh_to_drain.sh
  spmd/__init__.py
  spmd/tensor/dispatch.py
  spmd/tensor/ops/math_ops.py
  spmd/tensor/ops/tensor_ops.py
  spmd/tensor/ops/view_ops.py
  spmd/tensor/redistribute.py
  spmd/test/common_utils.py
  test/spmd/tensor/test_ddp.py
  test/spmd/tensor/test_device_mesh.py
  test/spmd/tensor/test_dtensor.py
  test/spmd/tensor/test_dtensor_ops.py
  test/spmd/tensor/test_math_ops.py
  test/spmd/tensor/test_matrix_ops.py
  test/spmd/tensor/test_megatron_example.py
  test/spmd/tensor/test_redistribute.py
  test/spmd/tensor/test_tensor_ops.py
  test/spmd/tensor/test_view_ops.py
Labels: cla signed, better engineering

#422 [spmd] try re-enable some tests
  spmd/tensor/redistribute.py
  test/spmd/tensor/test_matrix_ops.py
Labels: cla signed

#420 Enable NCCL in GPU docker CI
  .github/workflows/pippy_gpu_tests.sh
  .github/workflows/pippy_tests.yaml
Labels: cla signed
